version: '3'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--jetstream --http_port 8222"
    networks:
      - nats-network

  publisher:
    build: ./publisher
    depends_on:
      - nats
    networks:
      - nats-network
    environment:
      - NATS_URL=nats://nats:4222

  consumer1:
    build: ./consumer
    depends_on:
      - nats
    networks:
      - nats-network
    environment:
      - NATS_URL=nats://nats:4222
      - CONSUMER_ID=consumer1

  consumer2:
    build: ./consumer
    depends_on:
      - nats
    networks:
      - nats-network
    environment:
      - NATS_URL=nats://nats:4222
      - CONSUMER_ID=consumer2

  consumer3:
    build: ./consumer
    depends_on:
      - nats
    networks:
      - nats-network
    environment:
      - NATS_URL=nats://nats:4222
      - CONSUMER_ID=consumer3

  status-service:
    build: ./status-service
    depends_on:
      - nats
    networks:
      - nats-network
    environment:
      - NATS_URL=nats://nats:4222

networks:
  nats-network:
    driver: bridge
